[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.11", features = ["blocking"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
